### ISSUE TITLE
Should probably be in `finally` block

### ISSUE THREAD

**Issue by koraytugay** [oguzcam58/SearchAnagramWords#1]
https://github.com/oguzcam58/SearchAnagramWords/blob/a456dc7c9b23d2f8c62c6ce4eebfb00b52b0d672/src/com/oguzcam/searchanagram/algorithm/AnagramAlgorithm.java#L180

wdyt?

**Comment by oguzcam58** [comment]
Hi Koray,
Since I am defining closeables inside of try (...), and they are [autoClosables](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html), they are going to be closed in the implicit finally block :) However, deleteIfExist statement above meant to be run only there is no exception thrown. So, putting them inside of a finally block may result in unintended force for them to run. Thus, I think it's better the way it is implemented here.
